### PR TITLE
"local" SIGIL_PARAMS

### PR DESCRIPTION
**Pull request by tarzzz**
Adds `local` to SIGIL_PARAMS so that they are not in conflict from the parent method.

### CODE REVIEW

**Comment by tarzzz** [comment]
@josegonzalez Please review..

**Comment by tarzzz** [comment]
Tested with this change on-prem, the Liveness and Readiness probes are being set correctly on the test app:

image

**Comment by joaoalf** [comment]
:dancer: lgtm (fyi @josegonzalez )

**Comment by tarzzz** [comment]
Bumped version number as well, so that it can be installed in DDS..

**Pull request merged**
